# Use a JDK image
FROM openjdk:17-jdk-slim

# Set working directory
WORKDIR /app

# Copy target JAR (after build)
COPY target/*.jar app.jar

# Run the application
ENTRYPOINT ["java", "-jar", "app.jar"]

